### ISSUE TITLE
Specify minimum severity to comment

### ISSUE THREAD

**Issue by maxpowa** [jenkinsci/violation-comments-to-github-plugin#10]
Doesn't appear to be any way to specify a minimum severity, so all violations get commented on github regardless of severity. Preferably I'd like to be able to limit with something similar to the below snippet.
```
...
violationConfigs: [
    [ pattern: '.*/lint/eslint\\.xml$', reporter: 'CHECKSTYLE', minSeverity: 'HIGH' ],
]
...
```

**Comment by tomasbjerre** [comment]
I agree =) Would be a nice feature.

**Comment by tomasbjerre** [comment]
I'm releaseing this now in 1.38. Will be in the update sites within a few hours. Open issue again if any problems!
