### ISSUE TITLE
Found Violations are not getting published in Pull Request Comments

### ISSUE THREAD

**Issue by emoshaya-cognito** [jenkinsci/violation-comments-to-github-plugin#11]
I'm having issues with publishing violations from checkstyle,pmd and findbugs xml files back to github PR. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/8818542/24823789/5b294c4e-1bfa-11e7-90fe-fac9c212f6a0.png)

It's clearly picked up violations, but for some reason is not posting back to github PR comment. I've tried both username/password and OAuth2 token but none seem to work.

plugin config:

![image](https://cloud.githubusercontent.com/assets/8818542/24823794/66410dba-1bfa-11e7-8f04-dd11e20b716c.png)

What am I doing wrong?

**Comment by tomasbjerre** [comment]
Perhaps the violations found are on info-level. If you set "comment only if severity at least" to INFO, perhaps you will see something.

**Comment by emoshaya-cognito** [comment]
Hi @tomasbjerre I tried all the severity levels including the INFO one and still no comments are posted to Github. The Violations are a mix of high priority and medium priority warnings as in screenshot below:

![image](https://cloud.githubusercontent.com/assets/8818542/24826761/3f1039ce-1c35-11e7-8ec5-0a3f9c9e6d0e.png)

**Comment by tomasbjerre** [comment]
It might be that the PR is not merged when the static code analysis is performed. Perhaps its just the feature branch being built. It has to be merged into the target branch first (without that merge-commit being pushed). Otherwise the lines reported will not match the lines in the PR.

A quick test would be to rebase the feature-branch on top of the target branch.

Are you using the "GitHub Pull Request Builder Plugin" ?

**Comment by emoshaya-cognito** [comment]
@tomasbjerre I'm not quite sure I understand you.

I am using the Github Pull Request Builder Plugin. and I do the following steps:

Create a pull request from master with a simple change e.g. update README.me
The Pull Request Jenkins job gets triggered and starts building the maven projects with pmd, checkstyles and findbugs goals
The violation-comments-to-github plugin detects warnings in the output xml files
The plugin is configured to "Create one big comment with all violations"
"Comment only changed part of files" is unticked as I've not made changes to files that would have violations, only README.md
"Comment only if severity at least" is set to INFO

Output is following but not comments are pushed to Github Pull Request:

![image](https://cloud.githubusercontent.com/assets/8818542/24826913/d0aa632a-1c38-11e7-9c36-6daed8bb0b74.png)

**Comment by tomasbjerre** [comment]
Is the readme the only thing changed in the pull request?

**Comment by emoshaya-cognito** [comment]
yes the only changed file is README.md. However the branch has many warnings from other unchanged files and I thought having the following unticked would post the comment with the warnings.

![image](https://cloud.githubusercontent.com/assets/8818542/24829685/7abb6348-1c6e-11e7-9be0-2821bd62d5ed.png)

**Comment by tomasbjerre** [comment]
No. It will always only comment changed files. An optionally only comment the changed parts of those files.

**Comment by emoshaya-cognito** [comment]
@tomasbjerre thank you for your explanation! I now understand where I went wrong and misunderstood the purpose of the "Comment only changed part of files" field. This is now working as you suggested with violations in changed files.

**Comment by reintroducing** [comment]
I'm having a similar issue. I have `checkstyle-eslint.xml` and `checkstyle-stylelint.xml` files generated at the root when errors occur. I'm using the CHECKSTYLE pattern `.*checkstyle\-.*\.xml` but I'm getting no comments reported in GitHub. Here is the output in jenkins:

```
19:53:30 ---
19:53:30 --- Jenkins Violation Comments to GitHub ---
19:53:30 ---
19:53:30 gitHubUrl: null
19:53:30 repositoryOwner: spothero
19:53:30 repositoryName: control-panel
19:53:30 pullRequestId: 114
19:53:30 usernamePasswordCredentialsId: true
19:53:30 username: false
19:53:30 password: false
19:53:30 useOAuth2TokenCredentials: false
19:53:30 oAuth2Token: false
19:53:30 createSingleFileComments: true
19:53:30 createCommentWithAllSingleFileComments: false
19:53:30 commentOnlyChangedContent: false
19:53:30 minSeverity: INFO
19:53:30 keepOldComments: false
19:53:30 Using username and password from credentials
19:53:30 Running Jenkins Violation Comments To GitHub
19:53:30 PR 114
19:53:30 Workspace: /home/jenkins/workspace/Control-Panel/Control-Panel-PR
19:53:30 Using username / password
19:53:30 PR: spothero/control-panel/114
```

I've tried all sorts of different settings for `gitHubUrl` but none of them worked. What am I missing?

**Comment by tomasbjerre** [comment]
If this is pipeline you need double \ so that you have \\- and \\.

**Comment by reintroducing** [comment]
@tomasbjerre i'm not exactly sure what you mean, could you elaborate a bit?

**Comment by tomasbjerre** [comment]
Are you configuring the plugin as a pipeline or with the configuration GUI?

If this is pipeline you need double \ so that you have `\\-` and `\\.`

**Comment by reintroducing** [comment]
I'm using the GUI just as pictured in the original post.

**Comment by tomasbjerre** [comment]
Did you specify something in the reporter field? It says optional but I suspect there might be an issue there.

**Comment by reintroducing** [comment]
I did not, and i'm not exactly sure what to specify. I have both a file output by ESLint and one by Stylelint. What value should i be putting in there then?

**Comment by tomasbjerre** [comment]
I would put "ESLint" and "StyleLint" as reporter.

**Comment by reintroducing** [comment]
How would that be put into the one box, comma separated list... or?

**Comment by tomasbjerre** [comment]
Put anything in it perhaps `Checkstyle`.

**Comment by reintroducing** [comment]
Right, but I mean do I put `ESLint, Stylelint` in that reporter box, or just `ESLint`, or just `Stylelint`? What's the expected format of the entry in there?

**Comment by tomasbjerre** [comment]
The *reporter* is optional. The parser name will be used if no reporter specified. It is intended to be the name of the tool reporting the violations. For example if Detekt is used to produce a checkstyle-report, then you may specify Detekt in the reporter field.

**Comment by reintroducing** [comment]
I put in ESLint and that worked. wow, wish I would have figured that out yesterday, would have saved me a day.

Thanks for going back and forth on this with me, really appreciate your help.

**Comment by btoconnor** [comment]
Hello, I know this issue is old but I'm seeing identical behavior on my project.

This is the ouput when we run this on a pull request:

```
gitHubUrl: 
repositoryOwner: [redacted]
repositoryName: [redacted]
pullRequestId: 12553
credentialsId: true
oAuth2Token: false
createSingleFileComments: true
createCommentWithAllSingleFileComments: true
commentOnlyChangedContent: true
minSeverity: INFO
keepOldComments: false
commentTemplate: 
Rubocop with pattern .*/checkstyle-result\.xml$
Using username / password
Running Jenkins Violation Comments To GitHub
PR 12553
Workspace: /home/jenkins/agent/workspace/[redacted]_pull_request_lint
Found 6 violations from ViolationConfig [pattern=.*/checkstyle-result\.xml$, reporter=Rubocop, parser=CHECKSTYLE].
PR: [redacted]/[redacted]/12553
```

It seems that it's picked up the violations from the `checkstyle-result.xml` file generated for checkstyle by rubocop, but I'm not getting any comments on the pull request itself.  My pull request has an error in the changed files of the pull request.

As you can see above, I've tried specifying the reporter field on the parser, but that didn't solve the issue.

Possibly worth noting is that I'm currently just re-running the tests on the same PR (I think like 20 times now) using "retest this please", but I don't think that would affect anything as the builds run from scratch each time.

**Comment by tomasbjerre** [comment]
Does "retest this please" perform the merge before doing analysis?

**Comment by btoconnor** [comment]
We're using Github Pull Request Builder, so I believe so.

The 6 violations reported in the logs above are from changes in that pull request, so I'm fairly certain that part is working properly.

**Comment by tomasbjerre** [comment]
The question is what lines are reported in that `checkstyle-result.xml`. If the merge is not performed, those lines will not match the lines in the diff of the pull request. And sinche you have `commentOnlyChangedContent: true` they will not be considered changed parts.

Perhaps settings `commentOnlyChangedContent: false` is a quick test of that.

**Comment by btoconnor** [comment]
Just gave that a try and still no comment on the PR:

```---
--- Jenkins Violation Comments to GitHub ---
---
gitHubUrl: 
repositoryOwner: [redacted]
repositoryName: [redacted]
pullRequestId: 12553
credentialsId: true
oAuth2Token: false
createSingleFileComments: true
createCommentWithAllSingleFileComments: true
commentOnlyChangedContent: false
minSeverity: INFO
keepOldComments: false
commentTemplate: 
Rubocop with pattern .*/checkstyle-result\.xml$
Using username / password
Running Jenkins Violation Comments To GitHub
PR 12553
Workspace: /home/jenkins/agent/workspace/[redacted]_pull_request_lint
Found 6 violations from ViolationConfig [pattern=.*/checkstyle-result\.xml$, reporter=Rubocop, parser=CHECKSTYLE].
PR: [redacted]/[redacted]/12553```

Is there anything else from the logs that I can provide that might shed some light here?

**Comment by tomasbjerre** [comment]
Of there are no obvious errors in the build log. You may check the global system log, available from the "manage jenkins" page.

Or somehting like http://localhost:8080/jenkins/log/all or http://jenkins-server/log/all

**Comment by btoconnor** [comment]
Not seeing anything obvious there, unfortunately.

**Comment by tomasbjerre** [comment]
I would have suspected the system log to contain something about connection refused or faulty credentials... Such errors are logged, not thrown: https://github.com/tomasbjerre/violation-comments-to-github-lib/blob/master/src/main/java/se/bjurr/violations/comments/github/lib/GitHubCommentsProvider.java#L70

Are you sure no proxy is needed or firewall blocking?

**Comment by btoconnor** [comment]
No proxy as far as I know. I think the credentials are correct because prior to commenting here I had bad credentials and those messages were showing in the logs.  With the current credentials set, there's nothing about that there.

This is an example from seeing that:

```
PR: [redacted]/[redacted]/12553
java.lang.RuntimeException: org.eclipse.egit.github.core.client.RequestException: Bad credentials (401)
	at se.bjurr.violations.comments.github.lib.GitHubCommentsProvider.<init>(GitHubCommentsProvider.java:58)
	at se.bjurr.violations.comments.github.lib.ViolationCommentsToGitHubApi.toPullRequest(ViolationCommentsToGitHubApi.java:139)
	at org.jenkinsci.plugins.jvctg.perform.JvctgPerformer.doPerform(JvctgPerformer.java:139)
	at org.jenkinsci.plugins.jvctg.perform.JvctgPerformer$1.invoke(JvctgPerformer.java:233)
	at org.jenkinsci.plugins.jvctg.perform.JvctgPerformer$1.invoke(JvctgPerformer.java:221)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2816)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.egit.github.core.client.RequestException: Bad credentials (401)
	at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:552)
	at org.eclipse.egit.github.core.client.GitHubClient.get(GitHubClient.java:740)
	at org.eclipse.egit.github.core.client.PageIterator.next(PageIterator.java:173)
	at org.eclipse.egit.github.core.service.GitHubService.getAll(GitHubService.java:151)
	at org.eclipse.egit.github.core.service.GitHubService.getAll(GitHubService.java:135)
	at org.eclipse.egit.github.core.service.PullRequestService.getCommits(PullRequestService.java:319)
	at se.bjurr.violations.comments.github.lib.GitHubCommentsProvider.<init>(GitHubCommentsProvider.java:55)
	... 14 more
```

**Comment by tomasbjerre** [comment]
Strange... well I don't have much ideas left. One thing might be to try the pipeline script in the README to try and comment my violations-test repository. See if that works.

```
node {
 def mvnHome = tool 'Maven 3.3.9'
 deleteDir()
 
 stage('Merge') {
  sh "git init"
  sh "git fetch --no-tags --progress git@git:group/reponame.git +refs/heads/*:refs/remotes/origin/* --depth=200"
  sh "git checkout origin/${env.targetBranch}"
  sh "git merge origin/${env.sourceBranch}"
  sh "git log --graph --abbrev-commit --max-count=10"
 }

 stage('Static code analysis') {
  sh "${mvnHome}/bin/mvn package -DskipTests -Dmaven.test.failure.ignore=false -Dsurefire.skip=true -Dmaven.compile.fork=true -Dmaven.javadoc.skip=true"

  step([
   $class: 'ViolationsToGitHubRecorder', 
   config: [
    gitHubUrl: 'https://api.github.com/', 
    repositoryOwner: 'tomasbjerre', 
    repositoryName: 'violations-test', 
    pullRequestId: '2', 

    // Only specify one of these!
    oAuth2Token: '',
    credentialsId: '',

    createCommentWithAllSingleFileComments: true, 
    createSingleFileComments: true, 
    commentOnlyChangedContent: true, 
    minSeverity: 'INFO',
    keepOldComments: false,
    violationConfigs: [
     [ pattern: '.*/checkstyle-result\\.xml$', parser: 'CHECKSTYLE', reporter: 'Checkstyle' ], 
     [ pattern: '.*/findbugsXml\\.xml$', parser: 'FINDBUGS', reporter: 'Findbugs' ], 
     [ pattern: '.*/pmd\\.xml$', parser: 'PMD', reporter: 'PMD' ], 
    ]
   ]
  ])
 }
}
```

**Comment by btoconnor** [comment]
I wasn't able to test this out on your test project, but I wanted to check if something else was out of whack.  I went to the Jenkins Credentials manager, and the credential that we're using (which is a username / password for GitHub) records as nothing as using it.  It notes that a plugin would need to cooperate to make that work.  Does this line up with what's expected between credentials and the plugin?

**Comment by btoconnor** [comment]
Okay, I'm not sure if any of this will help or if I'm just spiraling down more.

I tried setting (via the GUI, I'm not familiar enough with Jenkins to dive into the DSL at this time) the job explicitly to "merge before build":

![image](https://user-images.githubusercontent.com/81829/42604937-353cb42c-8543-11e8-8a70-fd9be035d0b6.png)

I tried both of ${ghprbActualCommit} and ${sha1}, neither seemed to really change the outcome materially here.

I also tried flipping the following settings:
![image](https://user-images.githubusercontent.com/81829/42604984-78547326-8543-11e8-83cc-fb4a8d2ac8b7.png)

I still don't see anything different from the console output that would suggest anything is going wrong, but nothing appears commented on GitHub at all.  I've confirmed that the username / password that's setup on the plugin are correct as well.

Not sure if there's any help you can provide at this point, I'm just sort of at a loss for why the comments aren't showing up.

**Comment by tomasbjerre** [comment]
I would check the build log to make sure the merge is performed correctly. The source branch should be merged into the target branch before analysis is performed.
