### ISSUE TITLE
Would be nice to support SwiftLint!

### ISSUE THREAD

**Issue by Kalvin126** [jenkinsci/violation-comments-to-github-plugin#13]
Realm's [SwiftLint](violation-comments-to-github-plugin) exports to xml, junit, json, etc

**Comment by tomasbjerre** [comment]
Do you have some example output?

**Comment by tomasbjerre** [comment]
I found an issue https://github.com/realm/SwiftLint/issues/712 that mentions the `--reporter checkstyle`.

So It should already be supported through the checkstyle format.

**Comment by Kalvin126** [comment]
ooh would be nice to add SwiftLint to the list of supported linters then

**Comment by tomasbjerre** [comment]
done
