### ISSUE TITLE
After new commit in pull request, new violations didn't show up in review comment

### ISSUE THREAD

**Issue by biaomingzhong** [jenkinsci/violation-comments-to-github-plugin#16]
In the pull request, which had trigger violation review comment before with 3 violations.

And my new commit bring more violations. In jenkins job console ,show 13 violations.

The problem is that this time plugin didn't comment anything

Is there something wrong in my configurations?

`Keep old comments`,
`Create one comment per violation`,
`Comment only changed part of files` is on

`Create one big comment with all violations` is off

**Comment by tomasbjerre** [comment]
Are you performing the merge before running the analysis?

**Comment by biaomingzhong** [comment]
Didn't merge. It's in same pull-request. Just add another commit

**Comment by tomasbjerre** [comment]
Jenkins must perform the merge before the analysis is performed. It is documented in the readme.

**Comment by biaomingzhong** [comment]
I am using https://github.com/jenkinsci/ghprb-plugin with `${ghprbActualCommit}` in my `Branch Specifier`. You are saying using `${sha1}` instead.

Why the lines didn't match?

**Comment by tomasbjerre** [comment]
Yes sha1 sounds like the way to go.

The lines does not match because the plugin comments on the diff. The diff is the merged state. So the analysis must be made on the merged state.

**Comment by biaomingzhong** [comment]
Thanks. Is there any fast guide for me  to custom this plugin for not meged state?

Because I am using `git diff --name-status --diff-filter=dr $targetBranch...$sourceBranch` to get the changed files and run some test.

Just to test the pr changed files before merged to let PR author knows what went wrong.

**Comment by biaomingzhong** [comment]
Most my test is just coding guidelines

**Comment by tomasbjerre** [comment]
I'm not saying you should push the merge-commit. Just perform the merge, run analysis. No push.

That will give the author information about violations in the PR.

It is all documented in the readme.

**Comment by biaomingzhong** [comment]
I understand the right way is to local test merge-commit. Thanks
