### ISSUE TITLE
Jenkins Config - Unable to choose credential from non-default credential store - CredentialsHelper.java

### ISSUE THREAD

**Issue by gmanfunky** [jenkinsci/violation-comments-to-github-plugin#19]
The friendly job config page widget only allows a choice of credentials from the default Jenkins credential store. This prevents selection of credentials from a per-folder restricted access credential store.

Yet, the config widget can be used to *create* a credential in another store (as seen below).

![image](https://user-images.githubusercontent.com/1102928/36514866-a820ab14-172b-11e8-8f8c-228ec5c01ea1.png)

Tested with Violation Comments to GitHub Plugin v1.57

**Comment by casz** [comment]
@tomasbjerre that is due to the fact you are not giving the ItemGroup a chance to be filled with anything but `NULL`

See the consumer guide here: https://github.com/jenkinsci/credentials-plugin/blob/master/docs/consumer.adoc search for `doFill` :)

**Comment by tomasbjerre** [comment]
I will start with the Stash / Bitbucket Server plugin.  @casz supplied a PR for that: https://github.com/jenkinsci/violation-comments-to-stash-plugin/pull/50

Then I'll make the same changes here and in the GitLab plugin...

**Comment by casz** [comment]
@tomasbjerre I'll happily give you a hand 😄 You might not like what I find 😝

**Comment by tomasbjerre** [comment]
I would happily accept PR:s for the others! It is more than welcome =)

**Comment by casz** [comment]
You take GitHub, I take GitLab? 👍

**Comment by tomasbjerre** [comment]
OK =) I will probably spend time on this at some point next week.

**Comment by tomasbjerre** [comment]
Released now as 1.58. Thanks again @casz !
