### ISSUE TITLE
Template for Github comments

### ISSUE THREAD

**Issue by sfontana** [jenkinsci/violation-comments-to-github-plugin#26]
It seems that github changed the parsing of the "tags".
While before `<12345>` used to be hidden in the comments, now these kind of tags are visible.
This means that at the end of the violation comment there's a number that looks strange without the context. A workaround would be prefixing the hash with a letter so `<a123456>` instead of just `<123456>`  (see the edit version of this comment).

Example:
**Reporter**: PYLINT
**Rule**: W0612(unused-variable)
**Severity**: WARN
**File**: packages/test/feed.py L131

Unused variable 'hello'

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<-114807220>*

*<the line below is invisible>*
<a-114807220>

On a related note: is it possible to change the template at all? For instance in my case the `File` line is not needed because the comment already is at the right place, moreover It would be nice to have the first 3 lines in one line (especially when you have many violations) e.g.:

```
PYLINT -WARN- W0612(unused-variable)
Unused variable 'hello'
```

Thank you for your patience, a part from this small issues the project is awesome and helps a lot!

**Comment by tomasbjerre** [comment]
There is an issue about that here: https://github.com/tomasbjerre/violation-comments-lib/issues/2

There is currently no way of changing the template.

**Comment by tomasbjerre** [comment]
I released this feature now in 1.60. Tell me how that works for you, I'll await that before adding it to the other plugins.

**Comment by sfontana** [comment]
It works great! Thank you so much for this.


Nitpicking: imo there is an unneeded newline after the template body.
This is due to the newline between the template body and the auto generated comment.

So it looks like this

![screen shot 2018-05-14 at 08 30 34](https://user-images.githubusercontent.com/6084566/39981989-2739d576-5753-11e8-904c-b1d6e770ef92.png)


instead of this

![screen shot 2018-05-14 at 08 30 09](https://user-images.githubusercontent.com/6084566/39981953-fc695da8-5752-11e8-97f5-87cb4cddb3b0.png)



So instead of
````
ERROR: E0401(import-error)
Unable to import &#39;langdetect&#39;

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a2011823699>*
````

it should be
```
ERROR: E0401(import-error)
Unable to import &#39;langdetect&#39;
*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a2011823699>*
```

**Comment by tomasbjerre** [comment]
Ok great!
