### ISSUE TITLE
Making review comment different from line comments

### ISSUE THREAD

**Issue by IvanAnishchuk** [jenkinsci/violation-comments-to-github-plugin#28]
I just started using your plugin, I have both `createSingleFileComments` and `createCommentWithAllSingleFileComments` enabled and everything seems too work (thanks, by the way, great plugin) and I like this particular configuration because single-line comments are the most useful for developers yet combining them in a review extremely helpful too. But I would very much prefer that review comment wasn't all single file comments. Personally, I'd prefer to put just some short summary there instead, like how many violations which parser found with which severity etc.

Is it too hard to add ability to set a separate template for `CommentWithAllSingleFileComments` and/or maybe add a completely separate boolean parameter and a template that could be used for the review comment that can be rendered with some sort of summary data?

It's not a critical feature for me but would be extremely helpful, thanks.

**Comment by tomasbjerre** [comment]
This is something that would need to be implemented in this lib: https://github.com/tomasbjerre/violation-comments-lib

It definitely sounds like a nice feature.

**Comment by IvanAnishchuk** [comment]
Ok, reposting there as jenkinsci/violation-comments-to-github-plugin/#28

**Comment by IvanAnishchuk** [comment]
Thanks @tomasbjerre ! Did I mention that this plugin is one of my new favorites?

And if you don't mind I would like to discuss a couple other small things, just something I wanted to run by you and not sure if it's worth a separate issue or where to post those (here or the lib). About statuses.

One is the review status (Approve/Request Changes/Comment), would it be possible to set that according to settings and severity of violations? Plugin already creates a review for `AllSingleFileComments` but it could be beneficial to mark (optionally) it as "Request Changes"

And another is how hard do you think it would be to implement an additional "check" (commit status) on github for violations? I mean these little things: 
![checks screenshot](https://user-images.githubusercontent.com/3095764/46822877-55511b00-cd95-11e8-89ae-de4cfea9c2ab.png)
there's the build status, of course, but it would be nicer if you can tell what is broken without clicking and also I don't like failing the builds over non-critical style violations (I usually set up some build steps that are skipped for failing builds and I'd prefer if they ran as long as tests are passing) and a check in addition to review comments, I think, is the ideal middle ground for some of the cases. But I'm not sure if it would complicate this plugin too much and whether it might be better to implement it differently (like a separate step provided by a separate plugin, although sharing data could be a nightmare).

Sorry if I'm flooding you too much with this requests. Just feeling a bit overenthusiastic about not having to comment on style violations in my reviews anymore :)

**Comment by tomasbjerre** [comment]
The library uses a [GitHub rest client from Eclipse](https://github.com/tomasbjerre/violation-comments-to-github-lib/blob/master/src/main/java/se/bjurr/violations/comments/github/lib/GitHubCommentsProvider.java). I don't know it it is possible to do with that client. If it is possible then this issue should be no problem to solve.

But this should be its own feature request here or at https://github.com/tomasbjerre/violation-comments-to-github-lib
