### ISSUE TITLE
How do I configure 'Pull Request ID' to be 'env.CHANGE_ID' if adding a plugin as a Post-build Action

### ISSUE THREAD

**Issue by bpohoriletz** [jenkinsci/violation-comments-to-github-plugin#34]
Hello,
Is there a way to set 'Pull Request ID' to be `env.CHANGE_ID` from the UI? As far as I can see it's always get stored as a single quoted string.
<img width="1082" alt="Screen Shot 2019-08-28 at 23 23 27" src="https://user-images.githubusercontent.com/213166/63890244-34b0a480-c9eb-11e9-9745-e07a8b3be83d.png">

**Comment by tomasbjerre** [comment]
Yes the pull request ID gets expanded here: https://github.com/jenkinsci/violation-comments-to-github-plugin/blob/master/src/main/java/org/jenkinsci/plugins/jvctg/perform/JvctgPerformer.java#L169

So you can do ``${CHANGE_ID}` to have that variable resolved.

**Comment by bpohoriletz** [comment]
Thank you!
