### ISSUE TITLE
Integrate Credentials Product

### ISSUE THREAD

**Issue by digitalbuddha** [jenkinsci/violation-comments-to-github-plugin#4]
Howdy, We wanted to add your plugin to Jenkins and got a 👎 from our Dev Ops due to lack of using the credentials plugin. Would it be possible to integrate with the credential plugin?

**Comment by tomasbjerre** [comment]
Yes, it would be possible. I wont have time for a while. PR:s are welcome =)

**Comment by digitalbuddha** [comment]
Will give it a stab this weekend. Thanks!

**Comment by tomasbjerre** [comment]
Did you look at this? I have given it a try. But, as usual, the Jenkins code is such crap... cannot find any documentation about it and the API is shit...

God news is I found this example:
https://github.com/jenkinsci/stash-pullrequest-builder-plugin/blob/master/src/main/java/stashpullrequestbuilder/stashpullrequestbuilder/StashBuildTrigger.java

**Comment by tomasbjerre** [comment]
Releasing this now in 1.11. Open issue again if any problems.
